### ISSUE TITLE
HUD Not displayed in Marathon 1

### ISSUE THREAD

**Issue by tarmacprefecture** [daniele-rapagnani/alephone-android#15]
Thank you for the release! The three games all run great and the initial load of the first Marathon is actually very snappy. Only issue is the HUD in M1 displays as a black bar, at least on my phone. M2 and Infinity display correctly.

**Comment by PaulShaggy** [comment]
First of all, many, many thanks on porting AlephOne to Android! I've tried to find a way to play Marathon on the go for years and now I finally can.

Regarding the matter at hand: I've compiled the branch with the baked filesystem to get the HUD working in Marathon 1 - and it does - but the game will now no longer load savegames... at least not in any reasonable timeframe (<5min).
This is not the case for Durandal and Infinity when using the baked-fs version. Those load savegames just fine (although it takes a few seconds).
Activating and deactivating plugins doesn't seem to affect the process as far as I could see.

I've used Java 11, CMake 3.14.4, NDK 18.1.5063045 and Gradle 5.4.1-all.
Did I do something wrong or can you reproduce this issue?

**Comment by daniele-rapagnani** [comment]
Hey @PaulShaggy! I haven't encountered this issue but I have to say that I didn't test the baked-fs fix thoroughly, that's why I didn't merge it yet, so it's entirely possibile that it interferes somehow with how saves are loaded in Marathon 1. 

I'm currently putting my energies in another project but I'll take a look at this soon I hope!

**Comment by PaulShaggy** [comment]
Small Update: 
I managed to compile Marathon 1 using the old M1A1 data files ( https://github.com/Aleph-One-Marathon/data-m1a1 )
This version of the game does have a HUD similar to Durandal and Infinite, and it's correctly displayed on Android. Saving and Loading also works.
On the other hand, it does now suffer from similarly long loading times as the other two games, because the size of the assets has increased.
Still, it might be an intermediate solution to play the game...

**Comment by daniele-rapagnani** [comment]
@PaulShaggy that's an interesting find nonetheless. Shapes, sounds, etc, should really be the same considering we are not using HD assets. I don't se why the old data files should slow everything down as with M2 or Infinity, this may be a clue to get a better understanding of the issue.
